import json
from loot import extractLoot

testTargets = [
    ('img/drops/bugged/01.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "guard pulled leather gloves", "value": 596, "real_value": null, "rarity": "common", "untuned": false, "level_req": 16, "impact_res": 33, "cryonae_res": 37, "arborae_res": 36, "tempestae_res": 32, "infernae_res": 40, "necromae_res": 38, "strength": null, "magic_chance": null, "magic_element": null, "faction": null, "profession": "guard"}'),
    ('img/drops/bugged/02.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "guard studded helmet", "value": 0, "real_value": null, "rarity": "rare", "untuned": false, "level_req": 16, "impact_res": 61, "cryonae_res": 59, "arborae_res": 70, "tempestae_res": 73, "infernae_res": 62, "necromae_res": 71, "strength": null, "magic_chance": null, "magic_element": null, "faction": null, "profession": "guard"}'),
    ('img/drops/bugged/03.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "battleaxe", "value": 0, "real_value": null, "rarity": "uncommon", "untuned": false, "level_req": 4, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 37, "magic_chance": 48, "magic_element": "necromae", "faction": "cryoknight", "profession": "minefighter"}'),
    ('img/drops/bugged/04.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "polished bone legs", "value": 5000, "real_value": null, "rarity": "rare", "untuned": false, "level_req": 15, "impact_res": 57, "cryonae_res": 42, "arborae_res": 67, "tempestae_res": 72, "infernae_res": 68, "necromae_res": 64, "strength": null, "magic_chance": null, "magic_element": null, "faction": "guardian", "profession": "guard"}'),
    ('img/drops/bugged/05.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "battleaxe", "value": 1000, "real_value": null, "rarity": "uncommon", "untuned": false, "level_req": 15, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 50, "magic_chance": 40, "magic_element": "necromae", "faction": "cryoknight", "profession": "guard"}'),
    ('img/drops/bugged/06.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "great helm", "value": 575, "real_value": null, "rarity": "common", "untuned": false, "level_req": 15, "impact_res": 26, "cryonae_res": 34, "arborae_res": 43, "tempestae_res": 19, "infernae_res": 42, "necromae_res": 26, "strength": null, "magic_chance": null, "magic_element": null, "faction": "cryoknight", "profession": "guard"}'),
    ('img/drops/bugged/07.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "metal buckler", "value": 575, "real_value": null, "rarity": "common", "untuned": false, "level_req": 15, "impact_res": 31, "cryonae_res": 33, "arborae_res": 38, "tempestae_res": 25, "infernae_res": 35, "necromae_res": 28, "strength": null, "magic_chance": null, "magic_element": null, "faction": "cryoknight", "profession": "guard"}'),
    ('img/drops/bugged/08.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "metal heater shield", "value": 575, "real_value": null, "rarity": "common", "untuned": false, "level_req": 15, "impact_res": 41, "cryonae_res": 27, "arborae_res": 33, "tempestae_res": 10, "infernae_res": 39, "necromae_res": 40, "strength": null, "magic_chance": null, "magic_element": null, "faction": "cryoknight", "profession": "guard"}'),
    ('img/drops/bugged/09.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "metal bow", "value": 804, "real_value": null, "rarity": "common", "untuned": false, "level_req": 16, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 33, "magic_chance": 30, "magic_element": "arborae", "faction": "cryoknight", "profession": "guard"}'),
    # 10 is broken and not really fixable!
    ('img/drops/bugged/10.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "plate gauntlets", "value": 0, "real_value": null, "rarity": "common", "untuned": false, "level_req": 16, "impact_res": 40, "cryonae_res": 39, "arborae_res": 34, "tempestae_res": 39, "infernae_res": 37, "necromae_res": null, "strength": null, "magic_chance": null, "magic_element": null, "faction": "cryoknight", "profession": "guard"}'),
    ('img/drops/bugged/11.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "metal heater shield", "value": 575, "real_value": null, "rarity": "common", "untuned": false, "level_req": 15, "impact_res": 41, "cryonae_res": 27, "arborae_res": 33, "tempestae_res": 10, "infernae_res": 39, "necromae_res": 40, "strength": null, "magic_chance": null, "magic_element": null, "faction": "cryoknight", "profession": "guard"}'),
    ('img/drops/bugged/12.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "shortsword", "value": 488, "real_value": null, "rarity": "common", "untuned": true, "level_req": 16, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 32, "magic_chance": 38, "magic_element": "infernae", "faction": "cryoknight", "profession": "guard"}'),
    ('img/drops/bugged/13.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "battleaxe", "value": 2000, "real_value": null, "rarity": "uncommon", "untuned": false, "level_req": 16, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 51, "magic_chance": 36, "magic_element": "necromae", "faction": "cryoknight", "profession": "guard"}'),
    ('img/drops/bugged/14.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "battleaxe", "value": 5000, "real_value": null, "rarity": "rare", "untuned": false, "level_req": 4, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 55, "magic_chance": 33, "magic_element": "necromae", "faction": "cryoknight", "profession": "guard"}'),
    ('img/drops/bugged/15.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "shortsword", "value": 685, "real_value": null, "rarity": "uncommon", "untuned": false, "level_req": 3, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 34, "magic_chance": 39, "magic_element": "infernae", "faction": "cryoknight", "profession": "guard"}'),
    # 16 is also broken, OCR can't read the number 7?
    ('img/drops/bugged/16.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "sallet helmet", "value": 0, "real_value": null, "rarity": "common", "untuned": false, "level_req": 3, "impact_res": 24, "cryonae_res": 31, "arborae_res": 23, "tempestae_res": 19, "infernae_res": 14, "necromae_res": 3440, "strength": null, "magic_chance": null, "magic_element": null, "faction": "cryoknight", "profession": "guard"}'),
    # ignore
    ('img/drops/bugged/17.png', ''),

    ('img/drops/guard/01.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "stonesheen robe bottom", "value": 2000, "real_value": null, "rarity": "rare", "untuned": false, "level_req": 0, "impact_res": 53, "cryonae_res": 59, "arborae_res": 34, "tempestae_res": 44, "infernae_res": 42, "necromae_res": 48, "strength": null, "magic_chance": null, "magic_element": null, "faction": "hammermage", "profession": "guard"}'),
    ('img/drops/guard/02.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "guard leather mail helmet", "value": 1000, "real_value": null, "rarity": "uncommon", "untuned": false, "level_req": 6, "impact_res": 46, "cryonae_res": 32, "arborae_res": 41, "tempestae_res": 37, "infernae_res": 41, "necromae_res": 49, "strength": null, "magic_chance": null, "magic_element": null, "faction": null, "profession": "guard"}'),
    ('img/drops/guard/03.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "guard ribbed torso", "value": 823, "real_value": null, "rarity": "uncommon", "untuned": false, "level_req": 2, "impact_res": 36, "cryonae_res": 35, "arborae_res": 39, "tempestae_res": 33, "infernae_res": 43, "necromae_res": 36, "strength": null, "magic_chance": null, "magic_element": null, "faction": null, "profession": "guard"}'),
    ('img/drops/guard/04.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "rib torso", "value": 2000, "real_value": null, "rarity": "rare", "untuned": false, "level_req": 0, "impact_res": 50, "cryonae_res": 36, "arborae_res": 58, "tempestae_res": 41, "infernae_res": 45, "necromae_res": 50, "strength": null, "magic_chance": null, "magic_element": null, "faction": "guardian", "profession": "guard"}'),
    ('img/drops/guard/05.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "guard tower shield", "value": 150, "real_value": null, "rarity": "epic", "untuned": false, "level_req": 12, "impact_res": 77, "cryonae_res": 82, "arborae_res": 72, "tempestae_res": 82, "infernae_res": 76, "necromae_res": 73, "strength": null, "magic_chance": null, "magic_element": null, "faction": null, "profession": "guard"}'),
    ('img/drops/guard/06.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "guard studded leather gloves", "value": 8000, "real_value": null, "rarity": "epic", "untuned": false, "level_req": 0, "impact_res": 62, "cryonae_res": 66, "arborae_res": 56, "tempestae_res": 59, "infernae_res": 73, "necromae_res": 74, "strength": null, "magic_chance": null, "magic_element": null, "faction": null, "profession": "guard"}'),
    ('img/drops/guard/07.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "guard\'s bow", "value": 0, "real_value": null, "rarity": "uncommon", "untuned": true, "level_req": 18, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 53, "magic_chance": 0, "magic_element": null, "faction": null, "profession": "guard"}'),
    ('img/drops/guard/08.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "guard tower shield", "value": 1000, "real_value": null, "rarity": "uncommon", "untuned": false, "level_req": 9, "impact_res": 54, "cryonae_res": 37, "arborae_res": 54, "tempestae_res": 44, "infernae_res": 38, "necromae_res": 37, "strength": null, "magic_chance": null, "magic_element": null, "faction": null, "profession": "guard"}'),
    ('img/drops/guard/09.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "guard\'s bow", "value": 0, "real_value": null, "rarity": "uncommon", "untuned": false, "level_req": 18, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 53, "magic_chance": 0, "magic_element": null, "faction": null, "profession": "guard"}'),
    ('img/drops/guard/10.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "guard leather mail legs", "value": 596, "real_value": null, "rarity": "common", "untuned": false, "level_req": 16, "impact_res": 31, "cryonae_res": 46, "arborae_res": 33, "tempestae_res": 27, "infernae_res": 37, "necromae_res": 42, "strength": null, "magic_chance": null, "magic_element": null, "faction": null, "profession": "guard"}'),
    ('img/drops/guard/11.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "guard steel toe boots", "value": 639, "real_value": null, "rarity": "common", "untuned": false, "level_req": 18, "impact_res": 42, "cryonae_res": 38, "arborae_res": 35, "tempestae_res": 35, "infernae_res": 41, "necromae_res": 37, "strength": null, "magic_chance": null, "magic_element": null, "faction": null, "profession": "guard"}'),
    ('img/drops/guard/12.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "guard\'s kanabo", "value": 1000, "real_value": null, "rarity": "uncommon", "untuned": false, "level_req": 10, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 42, "magic_chance": 30, "magic_element": "tempestae", "faction": null, "profession": "guard"}'),
    ('img/drops/guard/13.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "war hammer", "value": 3000, "real_value": null, "rarity": "uncommon", "untuned": false, "level_req": 57, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 87, "magic_chance": 88, "magic_element": "tempestae", "faction": "hammermage", "profession": "guard"}'),
    ('img/drops/guard/14.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "guard\'s halberd", "value": 40000, "real_value": null, "rarity": "rare", "untuned": false, "level_req": 4, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 54, "magic_chance": 41, "magic_element": "cryonae", "faction": null, "profession": "guard"}'),
    ('img/drops/guard/15.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "guard\'s bow", "value": 1000, "real_value": null, "rarity": "uncommon", "untuned": false, "level_req": 15, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 50, "magic_chance": 0, "magic_element": null, "faction": null, "profession": "guard"}'),
    ('img/drops/guard/16.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "guard\'s bow", "value": 986, "real_value": null, "rarity": "common", "untuned": false, "level_req": 22, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 42, "magic_chance": 0, "magic_element": null, "faction": null, "profession": "guard"}'),
    ('img/drops/guard/17.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "stone slab shield", "value": 0, "real_value": null, "rarity": "common", "untuned": false, "level_req": 49, "impact_res": 60, "cryonae_res": 69, "arborae_res": 50, "tempestae_res": 72, "infernae_res": 65, "necromae_res": 78, "strength": null, "magic_chance": null, "magic_element": null, "faction": "hammermage", "profession": "guard"}'),
    ('img/drops/guard/18.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "stone slab shield", "value": 0, "real_value": null, "rarity": "common", "untuned": false, "level_req": 50, "impact_res": 72, "cryonae_res": 74, "arborae_res": 44, "tempestae_res": 60, "infernae_res": 79, "necromae_res": 71, "strength": null, "magic_chance": null, "magic_element": null, "faction": "hammermage", "profession": "guard"}'),
    ('img/drops/guard/19.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "guard\'s sword", "value": 0, "real_value": null, "rarity": "uncommon", "untuned": false, "level_req": 16, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 51, "magic_chance": 0, "magic_element": null, "faction": null, "profession": "guard"}'),
    # BROKEN FOR NOW.
    ('img/drops/items/01.png', ''),
    ('img/drops/minefighter/01.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "rapier", "value": 2000, "real_value": null, "rarity": "rare", "untuned": false, "level_req": 1, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 47, "magic_chance": 80, "magic_element": "cryonae", "faction": "cryoknight", "profession": "minefighter"}'),
    ('img/drops/minefighter/02.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "broadsword", "value": 412, "real_value": null, "rarity": "common", "untuned": false, "level_req": 3, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 19, "magic_chance": 89, "magic_element": "cryonae", "faction": "cryoknight", "profession": "minefighter"}'),
    ('img/drops/minefighter/03.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "metal kite shield", "value": 913, "real_value": null, "rarity": "uncommon", "untuned": false, "level_req": 4, "impact_res": 34, "cryonae_res": 41, "arborae_res": 44, "tempestae_res": 14, "infernae_res": 38, "necromae_res": 43, "strength": null, "magic_chance": null, "magic_element": null, "faction": "cryoknight", "profession": "minefighter"}'),
    ('img/drops/minefighter/04.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "throwing twinblades", "value": 2000, "real_value": null, "rarity": "rare", "untuned": false, "level_req": 4, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 54, "magic_chance": 0, "magic_element": null, "faction": "cryoknight", "profession": "minefighter"}'),
    ('img/drops/minefighter/05.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "chainmail torso", "value": 361, "real_value": null, "rarity": "common", "untuned": false, "level_req": 4, "impact_res": 32, "cryonae_res": 34, "arborae_res": 23, "tempestae_res": 0, "infernae_res": 24, "necromae_res": 15, "strength": null, "magic_chance": null, "magic_element": null, "faction": "cryoknight", "profession": "minefighter"}'),
    ('img/drops/minefighter/06.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "shortsword", "value": 271, "real_value": null, "rarity": "common", "untuned": false, "level_req": 3, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 19, "magic_chance": 41, "magic_element": "infernae", "faction": "cryoknight", "profession": "minefighter"}'),
    # incorrect value, should be 4000
    ('img/drops/minefighter/07.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "stonesheen gloves", "value": 40000, "real_value": null, "rarity": "rare", "untuned": false, "level_req": 6, "impact_res": 60, "cryonae_res": 59, "arborae_res": 28, "tempestae_res": 55, "infernae_res": 58, "necromae_res": 56, "strength": null, "magic_chance": null, "magic_element": null, "faction": "hammermage", "profession": "minefighter"}'),
    ('img/drops/minefighter/08.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "chainmail torso", "value": 361, "real_value": null, "rarity": "common", "untuned": false, "level_req": 4, "impact_res": 32, "cryonae_res": 34, "arborae_res": 23, "tempestae_res": 0, "infernae_res": 24, "necromae_res": 15, "strength": null, "magic_chance": null, "magic_element": null, "faction": "cryoknight", "profession": "minefighter"}'),
    ('img/drops/minefighter/09.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "sallet helmet", "value": 3000, "real_value": null, "rarity": "rare", "untuned": false, "level_req": 4, "impact_res": 51, "cryonae_res": 57, "arborae_res": 55, "tempestae_res": 40, "infernae_res": 51, "necromae_res": 50, "strength": null, "magic_chance": null, "magic_element": null, "faction": "cryoknight", "profession": "minefighter"}'),
    ('img/drops/minefighter/10.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "plate gauntlets", "value": 344, "real_value": null, "rarity": "common", "untuned": false, "level_req": 3, "impact_res": 20, "cryonae_res": 23, "arborae_res": 16, "tempestae_res": 9, "infernae_res": 24, "necromae_res": 26, "strength": null, "magic_chance": null, "magic_element": null, "faction": "cryoknight", "profession": "minefighter"}'),
    ('img/drops/scout/01.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "guard studded legs", "value": 0, "real_value": null, "rarity": "uncommon", "untuned": false, "level_req": 21, "impact_res": 65, "cryonae_res": 60, "arborae_res": 51, "tempestae_res": 53, "infernae_res": 46, "necromae_res": 61, "strength": null, "magic_chance": null, "magic_element": null, "faction": null, "profession": "scout"}'),
    ('img/drops/scout/02.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "guard steel toe boots", "value": 4000, "real_value": null, "rarity": "rare", "untuned": false, "level_req": 6, "impact_res": 53, "cryonae_res": 66, "arborae_res": 62, "tempestae_res": 46, "infernae_res": 56, "necromae_res": 53, "strength": null, "magic_chance": null, "magic_element": null, "faction": null, "profession": "scout"}'),
    ('img/drops/scout/03.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "guard round shield", "value": 735, "real_value": null, "rarity": "uncommon", "untuned": false, "level_req": 0, "impact_res": 30, "cryonae_res": 35, "arborae_res": 45, "tempestae_res": 41, "infernae_res": 30, "necromae_res": 29, "strength": null, "magic_chance": null, "magic_element": null, "faction": null, "profession": "scout"}'),
    ('img/drops/scout/04.png', '{"type": "weapon", "coins_drop": null, "qty": null, "item": "guard\'s kanabo", "value": 19000, "real_value": null, "rarity": "epic", "untuned": false, "level_req": 18, "impact_res": null, "cryonae_res": null, "arborae_res": null, "tempestae_res": null, "infernae_res": null, "necromae_res": null, "strength": 79, "magic_chance": 41, "magic_element": "tempestae", "faction": null, "profession": "scout"}'),
    ('img/drops/scout/05.png', '{"type": "armor", "coins_drop": null, "qty": null, "item": "metal kite shield", "value": 4000, "real_value": null, "rarity": "rare", "untuned": false, "level_req": 6, "impact_res": 60, "cryonae_res": 58, "arborae_res": 47, "tempestae_res": 27, "infernae_res": 58, "necromae_res": 66, "strength": null, "magic_chance": null, "magic_element": null, "faction": "cryoknight", "profession": "scout"}'),
    ('img/drops/scout/06.png', ''),
    ('img/drops/scout/07.png', ''),
    ('img/drops/scout/08.png', ''),
    ('img/drops/scout/09.png', ''),
    ('img/drops/scout/10.png', ''),
    ('img/drops/scout/11.png', ''),
    ('img/drops/scout/12.png', ''),
    ('img/drops/scout/13.png', ''),
    ('img/drops/scout/14.png', ''),
    ('img/drops/scout/15.png', ''),
    ('img/drops/scout/16.png', ''),
    ('img/drops/uncategorised/Common Chainmail Torso.png', ''),
    ('img/drops/uncategorised/Common Plate Boots.png', ''),
    ('img/drops/uncategorised/Common Plate Torso.png', ''),
    ('img/drops/uncategorised/Epic Great Helm.png', ''),
    ('img/drops/uncategorised/Epic Guard Leather Mail Helmet.png', ''),
    ('img/drops/uncategorised/Epic Plate Legs.png', ''),
    ('img/drops/uncategorised/Rare Cuirass.png', ''),
    ('img/drops/uncategorised/Rare Guard Studded Leather Gloves.png', ''),
    ('img/drops/uncategorised/Rare Guard Tower Shield.png', ''),
    ('img/drops/uncategorised/Rare Metal Kite Shield.png', ''),
    ('img/drops/uncategorised/Rare Plate Boots (1).png', ''),
    ('img/drops/uncategorised/Rare Plate Boots.png', ''),
    ('img/drops/uncategorised/Rare Plate Gauntlets.png', ''),
    ('img/drops/uncategorised/Rare Sallet Helmet.png', ''),
    ('img/drops/uncategorised/Uncommon Chainmail Legs.png', ''),
    ('img/drops/uncategorised/Uncommon Metal Kite Shield.png', ''),
    ('img/drops/uncategorised/Uncommon Plate Gauntlets.png', ''),
    ('img/drops/uncategorised/Uncommon Plate Legs.png', ''),
    ('img/drops/watchperson/01.png', ''),
    ('img/drops/watchperson/02.png', ''),
]

if __name__ == '__main__':
    for file, result in testTargets:

        if len(result):
            loot = extractLoot(file, False)
            if result != json.dumps(loot):
                raise Exception(f'{file} does not match!')
            else:
                print(f'{file} - MATCH')

